// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/jcmanager.proto

package jcmanagerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED     CommandType = 0
	CommandType_COMMAND_TYPE_APPLY_CONFIG    CommandType = 1
	CommandType_COMMAND_TYPE_RESTART_SERVICE CommandType = 2
	CommandType_COMMAND_TYPE_RESTORE_BACKUP  CommandType = 3
	CommandType_COMMAND_TYPE_HEALTH_CHECK    CommandType = 4
	CommandType_COMMAND_TYPE_DEREGISTER      CommandType = 5
	CommandType_COMMAND_TYPE_FILE_READ       CommandType = 6
	CommandType_COMMAND_TYPE_FILE_WRITE      CommandType = 7
	CommandType_COMMAND_TYPE_FILE_LIST       CommandType = 8
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_APPLY_CONFIG",
		2: "COMMAND_TYPE_RESTART_SERVICE",
		3: "COMMAND_TYPE_RESTORE_BACKUP",
		4: "COMMAND_TYPE_HEALTH_CHECK",
		5: "COMMAND_TYPE_DEREGISTER",
		6: "COMMAND_TYPE_FILE_READ",
		7: "COMMAND_TYPE_FILE_WRITE",
		8: "COMMAND_TYPE_FILE_LIST",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":     0,
		"COMMAND_TYPE_APPLY_CONFIG":    1,
		"COMMAND_TYPE_RESTART_SERVICE": 2,
		"COMMAND_TYPE_RESTORE_BACKUP":  3,
		"COMMAND_TYPE_HEALTH_CHECK":    4,
		"COMMAND_TYPE_DEREGISTER":      5,
		"COMMAND_TYPE_FILE_READ":       6,
		"COMMAND_TYPE_FILE_WRITE":      7,
		"COMMAND_TYPE_FILE_LIST":       8,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_jcmanager_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_jcmanager_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{0}
}

type ResultStatus int32

const (
	ResultStatus_RESULT_STATUS_UNSPECIFIED ResultStatus = 0
	ResultStatus_RESULT_STATUS_SUCCESS     ResultStatus = 1
	ResultStatus_RESULT_STATUS_FAILED      ResultStatus = 2
	ResultStatus_RESULT_STATUS_TIMEOUT     ResultStatus = 3
	ResultStatus_RESULT_STATUS_SKIPPED     ResultStatus = 4
)

// Enum value maps for ResultStatus.
var (
	ResultStatus_name = map[int32]string{
		0: "RESULT_STATUS_UNSPECIFIED",
		1: "RESULT_STATUS_SUCCESS",
		2: "RESULT_STATUS_FAILED",
		3: "RESULT_STATUS_TIMEOUT",
		4: "RESULT_STATUS_SKIPPED",
	}
	ResultStatus_value = map[string]int32{
		"RESULT_STATUS_UNSPECIFIED": 0,
		"RESULT_STATUS_SUCCESS":     1,
		"RESULT_STATUS_FAILED":      2,
		"RESULT_STATUS_TIMEOUT":     3,
		"RESULT_STATUS_SKIPPED":     4,
	}
)

func (x ResultStatus) Enum() *ResultStatus {
	p := new(ResultStatus)
	*p = x
	return p
}

func (x ResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_jcmanager_proto_enumTypes[1].Descriptor()
}

func (ResultStatus) Type() protoreflect.EnumType {
	return &file_proto_jcmanager_proto_enumTypes[1]
}

func (x ResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultStatus.Descriptor instead.
func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{1}
}

type Ack struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerTimeUnix int64                  `protobuf:"varint,3,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_jcmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ack) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_jcmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	DisplayName      string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RegisteredAtUnix int64                  `protobuf:"varint,3,opt,name=registered_at_unix,json=registeredAtUnix,proto3" json:"registered_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_jcmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterResponse) GetRegisteredAtUnix() int64 {
	if x != nil {
		return x.RegisteredAtUnix
	}
	return 0
}

type WatchCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCommandsRequest) Reset() {
	*x = WatchCommandsRequest{}
	mi := &file_proto_jcmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCommandsRequest) ProtoMessage() {}

func (x *WatchCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCommandsRequest.ProtoReflect.Descriptor instead.
func (*WatchCommandsRequest) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{3}
}

func (x *WatchCommandsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *NodeStatus            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_jcmanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *CommandResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_proto_jcmanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{5}
}

func (x *ReportResultRequest) GetResult() *CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type NodeInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PrimaryIp      string                 `protobuf:"bytes,4,opt,name=primary_ip,json=primaryIp,proto3" json:"primary_ip,omitempty"`
	Os             string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Arch           string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	Kernel         string                 `protobuf:"bytes,7,opt,name=kernel,proto3" json:"kernel,omitempty"`
	AgentVersion   string                 `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ServiceFlavors []string               `protobuf:"bytes,9,rep,name=service_flavors,json=serviceFlavors,proto3" json:"service_flavors,omitempty"`
	AllowedPaths   []string               `protobuf:"bytes,10,rep,name=allowed_paths,json=allowedPaths,proto3" json:"allowed_paths,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_jcmanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{6}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *NodeInfo) GetPrimaryIp() string {
	if x != nil {
		return x.PrimaryIp
	}
	return ""
}

func (x *NodeInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodeInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *NodeInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *NodeInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *NodeInfo) GetServiceFlavors() []string {
	if x != nil {
		return x.ServiceFlavors
	}
	return nil
}

func (x *NodeInfo) GetAllowedPaths() []string {
	if x != nil {
		return x.AllowedPaths
	}
	return nil
}

type NodeStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentTimeUnix    int64                  `protobuf:"varint,2,opt,name=agent_time_unix,json=agentTimeUnix,proto3" json:"agent_time_unix,omitempty"`
	Online           bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	CpuPercent       float64                `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedBytes  uint64                 `protobuf:"varint,5,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,6,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskUsedBytes    uint64                 `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes   uint64                 `protobuf:"varint,8,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	Load_1           float64                `protobuf:"fixed64,9,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5           float64                `protobuf:"fixed64,10,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15          float64                `protobuf:"fixed64,11,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	ConfigError      string                 `protobuf:"bytes,12,opt,name=config_error,json=configError,proto3" json:"config_error,omitempty"`
	Services         []*ServiceStatus       `protobuf:"bytes,13,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_jcmanager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{7}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetAgentTimeUnix() int64 {
	if x != nil {
		return x.AgentTimeUnix
	}
	return 0
}

func (x *NodeStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *NodeStatus) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeStatus) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeStatus) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeStatus) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *NodeStatus) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *NodeStatus) GetLoad_1() float64 {
	if x != nil {
		return x.Load_1
	}
	return 0
}

func (x *NodeStatus) GetLoad_5() float64 {
	if x != nil {
		return x.Load_5
	}
	return 0
}

func (x *NodeStatus) GetLoad_15() float64 {
	if x != nil {
		return x.Load_15
	}
	return 0
}

func (x *NodeStatus) GetConfigError() string {
	if x != nil {
		return x.ConfigError
	}
	return ""
}

func (x *NodeStatus) GetServices() []*ServiceStatus {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Listening     bool                   `protobuf:"varint,3,opt,name=listening,proto3" json:"listening,omitempty"`
	ListenPort    uint32                 `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,5,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_proto_jcmanager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ServiceStatus) GetListening() bool {
	if x != nil {
		return x.Listening
	}
	return false
}

func (x *ServiceStatus) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *ServiceStatus) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *ServiceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Command struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type           CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=jcmanager.v1.CommandType" json:"type,omitempty"`
	IssuedAtUnix   int64                  `protobuf:"varint,3,opt,name=issued_at_unix,json=issuedAtUnix,proto3" json:"issued_at_unix,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_ApplyConfig
	//	*Command_RestartService
	//	*Command_RestoreBackup
	//	*Command_HealthCheck
	//	*Command_Deregister
	//	*Command_FileRead
	//	*Command_FileWrite
	//	*Command_FileList
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_jcmanager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{9}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetIssuedAtUnix() int64 {
	if x != nil {
		return x.IssuedAtUnix
	}
	return 0
}

func (x *Command) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetApplyConfig() *ApplyConfigCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_ApplyConfig); ok {
			return x.ApplyConfig
		}
	}
	return nil
}

func (x *Command) GetRestartService() *RestartServiceCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_RestartService); ok {
			return x.RestartService
		}
	}
	return nil
}

func (x *Command) GetRestoreBackup() *RestoreBackupCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_RestoreBackup); ok {
			return x.RestoreBackup
		}
	}
	return nil
}

func (x *Command) GetHealthCheck() *HealthCheckCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

func (x *Command) GetDeregister() *DeregisterCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Deregister); ok {
			return x.Deregister
		}
	}
	return nil
}

func (x *Command) GetFileRead() *FileReadCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_FileRead); ok {
			return x.FileRead
		}
	}
	return nil
}

func (x *Command) GetFileWrite() *FileWriteCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_FileWrite); ok {
			return x.FileWrite
		}
	}
	return nil
}

func (x *Command) GetFileList() *FileListCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_FileList); ok {
			return x.FileList
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_ApplyConfig struct {
	ApplyConfig *ApplyConfigCommand `protobuf:"bytes,10,opt,name=apply_config,json=applyConfig,proto3,oneof"`
}

type Command_RestartService struct {
	RestartService *RestartServiceCommand `protobuf:"bytes,11,opt,name=restart_service,json=restartService,proto3,oneof"`
}

type Command_RestoreBackup struct {
	RestoreBackup *RestoreBackupCommand `protobuf:"bytes,12,opt,name=restore_backup,json=restoreBackup,proto3,oneof"`
}

type Command_HealthCheck struct {
	HealthCheck *HealthCheckCommand `protobuf:"bytes,13,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

type Command_Deregister struct {
	Deregister *DeregisterCommand `protobuf:"bytes,14,opt,name=deregister,proto3,oneof"`
}

type Command_FileRead struct {
	FileRead *FileReadCommand `protobuf:"bytes,15,opt,name=file_read,json=fileRead,proto3,oneof"`
}

type Command_FileWrite struct {
	FileWrite *FileWriteCommand `protobuf:"bytes,16,opt,name=file_write,json=fileWrite,proto3,oneof"`
}

type Command_FileList struct {
	FileList *FileListCommand `protobuf:"bytes,17,opt,name=file_list,json=fileList,proto3,oneof"`
}

func (*Command_ApplyConfig) isCommand_Payload() {}

func (*Command_RestartService) isCommand_Payload() {}

func (*Command_RestoreBackup) isCommand_Payload() {}

func (*Command_HealthCheck) isCommand_Payload() {}

func (*Command_Deregister) isCommand_Payload() {}

func (*Command_FileRead) isCommand_Payload() {}

func (*Command_FileWrite) isCommand_Payload() {}

func (*Command_FileList) isCommand_Payload() {}

type ApplyConfigCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceName       string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Path              string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content           []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RestartAfterWrite bool                   `protobuf:"varint,4,opt,name=restart_after_write,json=restartAfterWrite,proto3" json:"restart_after_write,omitempty"`
	CreateBackup      bool                   `protobuf:"varint,5,opt,name=create_backup,json=createBackup,proto3" json:"create_backup,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApplyConfigCommand) Reset() {
	*x = ApplyConfigCommand{}
	mi := &file_proto_jcmanager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigCommand) ProtoMessage() {}

func (x *ApplyConfigCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigCommand.ProtoReflect.Descriptor instead.
func (*ApplyConfigCommand) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{10}
}

func (x *ApplyConfigCommand) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ApplyConfigCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ApplyConfigCommand) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ApplyConfigCommand) GetRestartAfterWrite() bool {
	if x != nil {
		return x.RestartAfterWrite
	}
	return false
}

func (x *ApplyConfigCommand) GetCreateBackup() bool {
	if x != nil {
		return x.CreateBackup
	}
	return false
}

type RestartServiceCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServiceCommand) Reset() {
	*x = RestartServiceCommand{}
	mi := &file_proto_jcmanager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServiceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServiceCommand) ProtoMessage() {}

func (x *RestartServiceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServiceCommand.ProtoReflect.Descriptor instead.
func (*RestartServiceCommand) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{11}
}

func (x *RestartServiceCommand) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type RestoreBackupCommand struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceName         string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	BackupPath          string                 `protobuf:"bytes,2,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	RestartAfterRestore bool                   `protobuf:"varint,3,opt,name=restart_after_restore,json=restartAfterRestore,proto3" json:"restart_after_restore,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RestoreBackupCommand) Reset() {
	*x = RestoreBackupCommand{}
	mi := &file_proto_jcmanager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupCommand) ProtoMessage() {}

func (x *RestoreBackupCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupCommand.ProtoReflect.Descriptor instead.
func (*RestoreBackupCommand) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{12}
}

func (x *RestoreBackupCommand) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RestoreBackupCommand) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *RestoreBackupCommand) GetRestartAfterRestore() bool {
	if x != nil {
		return x.RestartAfterRestore
	}
	return false
}

type HealthCheckCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ExpectedPort  uint32                 `protobuf:"varint,2,opt,name=expected_port,json=expectedPort,proto3" json:"expected_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckCommand) Reset() {
	*x = HealthCheckCommand{}
	mi := &file_proto_jcmanager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckCommand) ProtoMessage() {}

func (x *HealthCheckCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckCommand.ProtoReflect.Descriptor instead.
func (*HealthCheckCommand) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckCommand) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthCheckCommand) GetExpectedPort() uint32 {
	if x != nil {
		return x.ExpectedPort
	}
	return 0
}

type DeregisterCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopAgent     bool                   `protobuf:"varint,1,opt,name=stop_agent,json=stopAgent,proto3" json:"stop_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterCommand) Reset() {
	*x = DeregisterCommand{}
	mi := &file_proto_jcmanager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterCommand) ProtoMessage() {}

func (x *DeregisterCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterCommand.ProtoReflect.Descriptor instead.
func (*DeregisterCommand) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{14}
}

func (x *DeregisterCommand) GetStopAgent() bool {
	if x != nil {
		return x.StopAgent
	}
	return false
}

type FileReadCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadCommand) Reset() {
	*x = FileReadCommand{}
	mi := &file_proto_jcmanager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadCommand) ProtoMessage() {}

func (x *FileReadCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadCommand.ProtoReflect.Descriptor instead.
func (*FileReadCommand) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{15}
}

func (x *FileReadCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileWriteCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Path              string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content           []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateBackup      bool                   `protobuf:"varint,3,opt,name=create_backup,json=createBackup,proto3" json:"create_backup,omitempty"`
	RestartAfterWrite bool                   `protobuf:"varint,4,opt,name=restart_after_write,json=restartAfterWrite,proto3" json:"restart_after_write,omitempty"`
	ServiceName       string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileWriteCommand) Reset() {
	*x = FileWriteCommand{}
	mi := &file_proto_jcmanager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteCommand) ProtoMessage() {}

func (x *FileWriteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteCommand.ProtoReflect.Descriptor instead.
func (*FileWriteCommand) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{16}
}

func (x *FileWriteCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileWriteCommand) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileWriteCommand) GetCreateBackup() bool {
	if x != nil {
		return x.CreateBackup
	}
	return false
}

func (x *FileWriteCommand) GetRestartAfterWrite() bool {
	if x != nil {
		return x.RestartAfterWrite
	}
	return false
}

func (x *FileWriteCommand) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type FileListCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListCommand) Reset() {
	*x = FileListCommand{}
	mi := &file_proto_jcmanager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListCommand) ProtoMessage() {}

func (x *FileListCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListCommand.ProtoReflect.Descriptor instead.
func (*FileListCommand) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{17}
}

func (x *FileListCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CommandResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CommandId         string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type              CommandType            `protobuf:"varint,3,opt,name=type,proto3,enum=jcmanager.v1.CommandType" json:"type,omitempty"`
	Status            ResultStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=jcmanager.v1.ResultStatus" json:"status,omitempty"`
	Message           string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Stdout            string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr            string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	BackupPath        string                 `protobuf:"bytes,8,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	Changed           bool                   `protobuf:"varint,9,opt,name=changed,proto3" json:"changed,omitempty"`
	HealthCheckPassed bool                   `protobuf:"varint,10,opt,name=health_check_passed,json=healthCheckPassed,proto3" json:"health_check_passed,omitempty"`
	ReportedAtUnix    int64                  `protobuf:"varint,11,opt,name=reported_at_unix,json=reportedAtUnix,proto3" json:"reported_at_unix,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CommandResult_FileRead
	//	*CommandResult_FileWrite
	//	*CommandResult_FileList
	Payload       isCommandResult_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_jcmanager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{18}
}

func (x *CommandResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *CommandResult) GetStatus() ResultStatus {
	if x != nil {
		return x.Status
	}
	return ResultStatus_RESULT_STATUS_UNSPECIFIED
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *CommandResult) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *CommandResult) GetHealthCheckPassed() bool {
	if x != nil {
		return x.HealthCheckPassed
	}
	return false
}

func (x *CommandResult) GetReportedAtUnix() int64 {
	if x != nil {
		return x.ReportedAtUnix
	}
	return 0
}

func (x *CommandResult) GetPayload() isCommandResult_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandResult) GetFileRead() *FileReadResponse {
	if x != nil {
		if x, ok := x.Payload.(*CommandResult_FileRead); ok {
			return x.FileRead
		}
	}
	return nil
}

func (x *CommandResult) GetFileWrite() *FileWriteResponse {
	if x != nil {
		if x, ok := x.Payload.(*CommandResult_FileWrite); ok {
			return x.FileWrite
		}
	}
	return nil
}

func (x *CommandResult) GetFileList() *FileListResponse {
	if x != nil {
		if x, ok := x.Payload.(*CommandResult_FileList); ok {
			return x.FileList
		}
	}
	return nil
}

type isCommandResult_Payload interface {
	isCommandResult_Payload()
}

type CommandResult_FileRead struct {
	FileRead *FileReadResponse `protobuf:"bytes,20,opt,name=file_read,json=fileRead,proto3,oneof"`
}

type CommandResult_FileWrite struct {
	FileWrite *FileWriteResponse `protobuf:"bytes,21,opt,name=file_write,json=fileWrite,proto3,oneof"`
}

type CommandResult_FileList struct {
	FileList *FileListResponse `protobuf:"bytes,22,opt,name=file_list,json=fileList,proto3,oneof"`
}

func (*CommandResult_FileRead) isCommandResult_Payload() {}

func (*CommandResult_FileWrite) isCommandResult_Payload() {}

func (*CommandResult_FileList) isCommandResult_Payload() {}

type FileReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadRequest) Reset() {
	*x = FileReadRequest{}
	mi := &file_proto_jcmanager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadRequest) ProtoMessage() {}

func (x *FileReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadRequest.ProtoReflect.Descriptor instead.
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{19}
}

func (x *FileReadRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FileReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ModTimeUnix   int64                  `protobuf:"varint,4,opt,name=mod_time_unix,json=modTimeUnix,proto3" json:"mod_time_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadResponse) Reset() {
	*x = FileReadResponse{}
	mi := &file_proto_jcmanager_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadResponse) ProtoMessage() {}

func (x *FileReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadResponse.ProtoReflect.Descriptor instead.
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{20}
}

func (x *FileReadResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileReadResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileReadResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileReadResponse) GetModTimeUnix() int64 {
	if x != nil {
		return x.ModTimeUnix
	}
	return 0
}

type FileWriteRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Path              string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content           []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateBackup      bool                   `protobuf:"varint,4,opt,name=create_backup,json=createBackup,proto3" json:"create_backup,omitempty"`
	RestartAfterWrite bool                   `protobuf:"varint,5,opt,name=restart_after_write,json=restartAfterWrite,proto3" json:"restart_after_write,omitempty"`
	ServiceName       string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileWriteRequest) Reset() {
	*x = FileWriteRequest{}
	mi := &file_proto_jcmanager_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteRequest) ProtoMessage() {}

func (x *FileWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteRequest.ProtoReflect.Descriptor instead.
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{21}
}

func (x *FileWriteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FileWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileWriteRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileWriteRequest) GetCreateBackup() bool {
	if x != nil {
		return x.CreateBackup
	}
	return false
}

func (x *FileWriteRequest) GetRestartAfterWrite() bool {
	if x != nil {
		return x.RestartAfterWrite
	}
	return false
}

func (x *FileWriteRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type FileWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BackupPath    string                 `protobuf:"bytes,2,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	Restarted     bool                   `protobuf:"varint,3,opt,name=restarted,proto3" json:"restarted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteResponse) Reset() {
	*x = FileWriteResponse{}
	mi := &file_proto_jcmanager_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteResponse) ProtoMessage() {}

func (x *FileWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteResponse.ProtoReflect.Descriptor instead.
func (*FileWriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{22}
}

func (x *FileWriteResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileWriteResponse) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *FileWriteResponse) GetRestarted() bool {
	if x != nil {
		return x.Restarted
	}
	return false
}

type FileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_proto_jcmanager_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{23}
}

func (x *FileListRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FileListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_proto_jcmanager_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{24}
}

func (x *FileListResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ModTimeUnix   int64                  `protobuf:"varint,5,opt,name=mod_time_unix,json=modTimeUnix,proto3" json:"mod_time_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_proto_jcmanager_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jcmanager_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_proto_jcmanager_proto_rawDescGZIP(), []int{25}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileEntry) GetModTimeUnix() int64 {
	if x != nil {
		return x.ModTimeUnix
	}
	return 0
}

var File_proto_jcmanager_proto protoreflect.FileDescriptor

const file_proto_jcmanager_proto_rawDesc = "" +
	"\n" +
	"\x15proto/jcmanager.proto\x12\fjcmanager.v1\"Y\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x10server_time_unix\x18\x03 \x01(\x03R\x0eserverTimeUnix\"S\n" +
	"\x0fRegisterRequest\x12*\n" +
	"\x04node\x18\x01 \x01(\v2\x16.jcmanager.v1.NodeInfoR\x04node\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"|\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12,\n" +
	"\x12registered_at_unix\x18\x03 \x01(\x03R\x10registeredAtUnix\"/\n" +
	"\x14WatchCommandsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"D\n" +
	"\x10HeartbeatRequest\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.jcmanager.v1.NodeStatusR\x06status\"J\n" +
	"\x13ReportResultRequest\x123\n" +
	"\x06result\x18\x01 \x01(\v2\x1b.jcmanager.v1.CommandResultR\x06result\"\xb0\x02\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"primary_ip\x18\x04 \x01(\tR\tprimaryIp\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\x16\n" +
	"\x06kernel\x18\a \x01(\tR\x06kernel\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\x12'\n" +
	"\x0fservice_flavors\x18\t \x03(\tR\x0eserviceFlavors\x12#\n" +
	"\rallowed_paths\x18\n" +
	" \x03(\tR\fallowedPaths\"\xd5\x03\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12&\n" +
	"\x0fagent_time_unix\x18\x02 \x01(\x03R\ragentTimeUnix\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x01R\n" +
	"cpuPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x05 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x06 \x01(\x04R\x10memoryTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\b \x01(\x04R\x0ediskTotalBytes\x12\x15\n" +
	"\x06load_1\x18\t \x01(\x01R\x05load1\x12\x15\n" +
	"\x06load_5\x18\n" +
	" \x01(\x01R\x05load5\x12\x17\n" +
	"\aload_15\x18\v \x01(\x01R\x06load15\x12!\n" +
	"\fconfig_error\x18\f \x01(\tR\vconfigError\x127\n" +
	"\bservices\x18\r \x03(\v2\x1b.jcmanager.v1.ServiceStatusR\bservices\"\xb5\x01\n" +
	"\rServiceStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1c\n" +
	"\tlistening\x18\x03 \x01(\bR\tlistening\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\rR\n" +
	"listenPort\x12\x1f\n" +
	"\vconfig_path\x18\x05 \x01(\tR\n" +
	"configPath\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xdc\x05\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.jcmanager.v1.CommandTypeR\x04type\x12$\n" +
	"\x0eissued_at_unix\x18\x03 \x01(\x03R\fissuedAtUnix\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12E\n" +
	"\fapply_config\x18\n" +
	" \x01(\v2 .jcmanager.v1.ApplyConfigCommandH\x00R\vapplyConfig\x12N\n" +
	"\x0frestart_service\x18\v \x01(\v2#.jcmanager.v1.RestartServiceCommandH\x00R\x0erestartService\x12K\n" +
	"\x0erestore_backup\x18\f \x01(\v2\".jcmanager.v1.RestoreBackupCommandH\x00R\rrestoreBackup\x12E\n" +
	"\fhealth_check\x18\r \x01(\v2 .jcmanager.v1.HealthCheckCommandH\x00R\vhealthCheck\x12A\n" +
	"\n" +
	"deregister\x18\x0e \x01(\v2\x1f.jcmanager.v1.DeregisterCommandH\x00R\n" +
	"deregister\x12<\n" +
	"\tfile_read\x18\x0f \x01(\v2\x1d.jcmanager.v1.FileReadCommandH\x00R\bfileRead\x12?\n" +
	"\n" +
	"file_write\x18\x10 \x01(\v2\x1e.jcmanager.v1.FileWriteCommandH\x00R\tfileWrite\x12<\n" +
	"\tfile_list\x18\x11 \x01(\v2\x1d.jcmanager.v1.FileListCommandH\x00R\bfileListB\t\n" +
	"\apayload\"\xba\x01\n" +
	"\x12ApplyConfigCommand\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12.\n" +
	"\x13restart_after_write\x18\x04 \x01(\bR\x11restartAfterWrite\x12#\n" +
	"\rcreate_backup\x18\x05 \x01(\bR\fcreateBackup\":\n" +
	"\x15RestartServiceCommand\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\x8e\x01\n" +
	"\x14RestoreBackupCommand\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vbackup_path\x18\x02 \x01(\tR\n" +
	"backupPath\x122\n" +
	"\x15restart_after_restore\x18\x03 \x01(\bR\x13restartAfterRestore\"\\\n" +
	"\x12HealthCheckCommand\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12#\n" +
	"\rexpected_port\x18\x02 \x01(\rR\fexpectedPort\"2\n" +
	"\x11DeregisterCommand\x12\x1d\n" +
	"\n" +
	"stop_agent\x18\x01 \x01(\bR\tstopAgent\"%\n" +
	"\x0fFileReadCommand\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xb8\x01\n" +
	"\x10FileWriteCommand\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12#\n" +
	"\rcreate_backup\x18\x03 \x01(\bR\fcreateBackup\x12.\n" +
	"\x13restart_after_write\x18\x04 \x01(\bR\x11restartAfterWrite\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\"%\n" +
	"\x0fFileListCommand\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xd4\x04\n" +
	"\rCommandResult\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.jcmanager.v1.CommandTypeR\x04type\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.jcmanager.v1.ResultStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12\x1f\n" +
	"\vbackup_path\x18\b \x01(\tR\n" +
	"backupPath\x12\x18\n" +
	"\achanged\x18\t \x01(\bR\achanged\x12.\n" +
	"\x13health_check_passed\x18\n" +
	" \x01(\bR\x11healthCheckPassed\x12(\n" +
	"\x10reported_at_unix\x18\v \x01(\x03R\x0ereportedAtUnix\x12=\n" +
	"\tfile_read\x18\x14 \x01(\v2\x1e.jcmanager.v1.FileReadResponseH\x00R\bfileRead\x12@\n" +
	"\n" +
	"file_write\x18\x15 \x01(\v2\x1f.jcmanager.v1.FileWriteResponseH\x00R\tfileWrite\x12=\n" +
	"\tfile_list\x18\x16 \x01(\v2\x1e.jcmanager.v1.FileListResponseH\x00R\bfileListB\t\n" +
	"\apayload\">\n" +
	"\x0fFileReadRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x83\x01\n" +
	"\x10FileReadResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\"\n" +
	"\rmod_time_unix\x18\x04 \x01(\x03R\vmodTimeUnix\"\xd1\x01\n" +
	"\x10FileWriteRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12#\n" +
	"\rcreate_backup\x18\x04 \x01(\bR\fcreateBackup\x12.\n" +
	"\x13restart_after_write\x18\x05 \x01(\bR\x11restartAfterWrite\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\"f\n" +
	"\x11FileWriteResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vbackup_path\x18\x02 \x01(\tR\n" +
	"backupPath\x12\x1c\n" +
	"\trestarted\x18\x03 \x01(\bR\trestarted\">\n" +
	"\x0fFileListRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"E\n" +
	"\x10FileListResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.jcmanager.v1.FileEntryR\aentries\"\x8d\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\"\n" +
	"\rmod_time_unix\x18\x05 \x01(\x03R\vmodTimeUnix*\x9e\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMMAND_TYPE_APPLY_CONFIG\x10\x01\x12 \n" +
	"\x1cCOMMAND_TYPE_RESTART_SERVICE\x10\x02\x12\x1f\n" +
	"\x1bCOMMAND_TYPE_RESTORE_BACKUP\x10\x03\x12\x1d\n" +
	"\x19COMMAND_TYPE_HEALTH_CHECK\x10\x04\x12\x1b\n" +
	"\x17COMMAND_TYPE_DEREGISTER\x10\x05\x12\x1a\n" +
	"\x16COMMAND_TYPE_FILE_READ\x10\x06\x12\x1b\n" +
	"\x17COMMAND_TYPE_FILE_WRITE\x10\a\x12\x1a\n" +
	"\x16COMMAND_TYPE_FILE_LIST\x10\b*\x98\x01\n" +
	"\fResultStatus\x12\x1d\n" +
	"\x19RESULT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESULT_STATUS_SUCCESS\x10\x01\x12\x18\n" +
	"\x14RESULT_STATUS_FAILED\x10\x02\x12\x19\n" +
	"\x15RESULT_STATUS_TIMEOUT\x10\x03\x12\x19\n" +
	"\x15RESULT_STATUS_SKIPPED\x10\x042\xad\x02\n" +
	"\fAgentService\x12I\n" +
	"\bRegister\x12\x1d.jcmanager.v1.RegisterRequest\x1a\x1e.jcmanager.v1.RegisterResponse\x12>\n" +
	"\tHeartbeat\x12\x1e.jcmanager.v1.HeartbeatRequest\x1a\x11.jcmanager.v1.Ack\x12L\n" +
	"\rWatchCommands\x12\".jcmanager.v1.WatchCommandsRequest\x1a\x15.jcmanager.v1.Command0\x01\x12D\n" +
	"\fReportResult\x12!.jcmanager.v1.ReportResultRequest\x1a\x11.jcmanager.v1.AckB\x1dZ\x1bjcmanager/proto;jcmanagerpbb\x06proto3"

var (
	file_proto_jcmanager_proto_rawDescOnce sync.Once
	file_proto_jcmanager_proto_rawDescData []byte
)

func file_proto_jcmanager_proto_rawDescGZIP() []byte {
	file_proto_jcmanager_proto_rawDescOnce.Do(func() {
		file_proto_jcmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jcmanager_proto_rawDesc), len(file_proto_jcmanager_proto_rawDesc)))
	})
	return file_proto_jcmanager_proto_rawDescData
}

var file_proto_jcmanager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_jcmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_jcmanager_proto_goTypes = []any{
	(CommandType)(0),              // 0: jcmanager.v1.CommandType
	(ResultStatus)(0),             // 1: jcmanager.v1.ResultStatus
	(*Ack)(nil),                   // 2: jcmanager.v1.Ack
	(*RegisterRequest)(nil),       // 3: jcmanager.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 4: jcmanager.v1.RegisterResponse
	(*WatchCommandsRequest)(nil),  // 5: jcmanager.v1.WatchCommandsRequest
	(*HeartbeatRequest)(nil),      // 6: jcmanager.v1.HeartbeatRequest
	(*ReportResultRequest)(nil),   // 7: jcmanager.v1.ReportResultRequest
	(*NodeInfo)(nil),              // 8: jcmanager.v1.NodeInfo
	(*NodeStatus)(nil),            // 9: jcmanager.v1.NodeStatus
	(*ServiceStatus)(nil),         // 10: jcmanager.v1.ServiceStatus
	(*Command)(nil),               // 11: jcmanager.v1.Command
	(*ApplyConfigCommand)(nil),    // 12: jcmanager.v1.ApplyConfigCommand
	(*RestartServiceCommand)(nil), // 13: jcmanager.v1.RestartServiceCommand
	(*RestoreBackupCommand)(nil),  // 14: jcmanager.v1.RestoreBackupCommand
	(*HealthCheckCommand)(nil),    // 15: jcmanager.v1.HealthCheckCommand
	(*DeregisterCommand)(nil),     // 16: jcmanager.v1.DeregisterCommand
	(*FileReadCommand)(nil),       // 17: jcmanager.v1.FileReadCommand
	(*FileWriteCommand)(nil),      // 18: jcmanager.v1.FileWriteCommand
	(*FileListCommand)(nil),       // 19: jcmanager.v1.FileListCommand
	(*CommandResult)(nil),         // 20: jcmanager.v1.CommandResult
	(*FileReadRequest)(nil),       // 21: jcmanager.v1.FileReadRequest
	(*FileReadResponse)(nil),      // 22: jcmanager.v1.FileReadResponse
	(*FileWriteRequest)(nil),      // 23: jcmanager.v1.FileWriteRequest
	(*FileWriteResponse)(nil),     // 24: jcmanager.v1.FileWriteResponse
	(*FileListRequest)(nil),       // 25: jcmanager.v1.FileListRequest
	(*FileListResponse)(nil),      // 26: jcmanager.v1.FileListResponse
	(*FileEntry)(nil),             // 27: jcmanager.v1.FileEntry
}
var file_proto_jcmanager_proto_depIdxs = []int32{
	8,  // 0: jcmanager.v1.RegisterRequest.node:type_name -> jcmanager.v1.NodeInfo
	9,  // 1: jcmanager.v1.HeartbeatRequest.status:type_name -> jcmanager.v1.NodeStatus
	20, // 2: jcmanager.v1.ReportResultRequest.result:type_name -> jcmanager.v1.CommandResult
	10, // 3: jcmanager.v1.NodeStatus.services:type_name -> jcmanager.v1.ServiceStatus
	0,  // 4: jcmanager.v1.Command.type:type_name -> jcmanager.v1.CommandType
	12, // 5: jcmanager.v1.Command.apply_config:type_name -> jcmanager.v1.ApplyConfigCommand
	13, // 6: jcmanager.v1.Command.restart_service:type_name -> jcmanager.v1.RestartServiceCommand
	14, // 7: jcmanager.v1.Command.restore_backup:type_name -> jcmanager.v1.RestoreBackupCommand
	15, // 8: jcmanager.v1.Command.health_check:type_name -> jcmanager.v1.HealthCheckCommand
	16, // 9: jcmanager.v1.Command.deregister:type_name -> jcmanager.v1.DeregisterCommand
	17, // 10: jcmanager.v1.Command.file_read:type_name -> jcmanager.v1.FileReadCommand
	18, // 11: jcmanager.v1.Command.file_write:type_name -> jcmanager.v1.FileWriteCommand
	19, // 12: jcmanager.v1.Command.file_list:type_name -> jcmanager.v1.FileListCommand
	0,  // 13: jcmanager.v1.CommandResult.type:type_name -> jcmanager.v1.CommandType
	1,  // 14: jcmanager.v1.CommandResult.status:type_name -> jcmanager.v1.ResultStatus
	22, // 15: jcmanager.v1.CommandResult.file_read:type_name -> jcmanager.v1.FileReadResponse
	24, // 16: jcmanager.v1.CommandResult.file_write:type_name -> jcmanager.v1.FileWriteResponse
	26, // 17: jcmanager.v1.CommandResult.file_list:type_name -> jcmanager.v1.FileListResponse
	27, // 18: jcmanager.v1.FileListResponse.entries:type_name -> jcmanager.v1.FileEntry
	3,  // 19: jcmanager.v1.AgentService.Register:input_type -> jcmanager.v1.RegisterRequest
	6,  // 20: jcmanager.v1.AgentService.Heartbeat:input_type -> jcmanager.v1.HeartbeatRequest
	5,  // 21: jcmanager.v1.AgentService.WatchCommands:input_type -> jcmanager.v1.WatchCommandsRequest
	7,  // 22: jcmanager.v1.AgentService.ReportResult:input_type -> jcmanager.v1.ReportResultRequest
	4,  // 23: jcmanager.v1.AgentService.Register:output_type -> jcmanager.v1.RegisterResponse
	2,  // 24: jcmanager.v1.AgentService.Heartbeat:output_type -> jcmanager.v1.Ack
	11, // 25: jcmanager.v1.AgentService.WatchCommands:output_type -> jcmanager.v1.Command
	2,  // 26: jcmanager.v1.AgentService.ReportResult:output_type -> jcmanager.v1.Ack
	23, // [23:27] is the sub-list for method output_type
	19, // [19:23] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_jcmanager_proto_init() }
func file_proto_jcmanager_proto_init() {
	if File_proto_jcmanager_proto != nil {
		return
	}
	file_proto_jcmanager_proto_msgTypes[9].OneofWrappers = []any{
		(*Command_ApplyConfig)(nil),
		(*Command_RestartService)(nil),
		(*Command_RestoreBackup)(nil),
		(*Command_HealthCheck)(nil),
		(*Command_Deregister)(nil),
		(*Command_FileRead)(nil),
		(*Command_FileWrite)(nil),
		(*Command_FileList)(nil),
	}
	file_proto_jcmanager_proto_msgTypes[18].OneofWrappers = []any{
		(*CommandResult_FileRead)(nil),
		(*CommandResult_FileWrite)(nil),
		(*CommandResult_FileList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jcmanager_proto_rawDesc), len(file_proto_jcmanager_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_jcmanager_proto_goTypes,
		DependencyIndexes: file_proto_jcmanager_proto_depIdxs,
		EnumInfos:         file_proto_jcmanager_proto_enumTypes,
		MessageInfos:      file_proto_jcmanager_proto_msgTypes,
	}.Build()
	File_proto_jcmanager_proto = out.File
	file_proto_jcmanager_proto_goTypes = nil
	file_proto_jcmanager_proto_depIdxs = nil
}
